### PR TITLE
Update "SK Flow" -> "tf.contrib.learn"

### PR DESCRIPTION
**Pull request by stevenschmatz**
The TensorFlow team changed the name for the project.

### CODE REVIEW

**Comment by jtoy** [comment]
there is a bug in your diff.

**Comment by stevenschmatz** [comment]
Really? Where?

**Comment by jtoy** [comment]
tf.contrib.learn: https://github.com/jtoy/awesome-tensorflow/pull/99/files

**Comment by stevenschmatz** [comment]
Hahaha good catch. I can't believe I messed up a typo fix.

**Pull request merged**
